### ISSUE TITLE
feature after relu or before relu?

### ISSUE THREAD

**Issue by twmht** [ZJCV/KnowledgeReview#4]
Hi,

I found out that you extract the feature before relu (https://github.com/ZJCV/KnowledgeReview/blob/master/rfd/model/resnet/resnet.py#L35).

But from the offical repo they extract the feature after relu (https://github.com/dvlab-research/ReviewKD/blob/master/CIFAR-100/model/resnet_cifar.py#L186)

Why did you make this difference?

**Comment by zjykzj** [comment]
> Hi,
> 
> I found out that you extract the feature before relu (https://github.com/ZJCV/KnowledgeReview/blob/master/rfd/model/resnet/resnet.py#L35).
> 
> But from the offical repo they extract the feature after relu (https://github.com/dvlab-research/ReviewKD/blob/master/CIFAR-100/model/resnet_cifar.py#L186)
> 
> Why did you make this difference?

> 

In original implementation, it is also get the feature before relu, see

1. https://github.com/dvlab-research/ReviewKD/blob/cede6ea6387ae9b6127de0e561507177bf19c11e/CIFAR-100/model/resnet_cifar.py#L95
2. https://github.com/dvlab-research/ReviewKD/blob/cede6ea6387ae9b6127de0e561507177bf19c11e/CIFAR-100/model/resnet_cifar.py#L52

This operation is derived from `A Comprehensive Overhaul of Feature Distillation`. Because `relu` will filter all negative values, and this may be useful for learning.

**Comment by twmht** [comment]
@zjykzj 

yup. I was wrong so I have closed this issue.  thanks for your comment.
